'use strict';
const $=id=>document.getElementById(id),sleep=ms=>new Promise(r=>setTimeout(r,ms));
let target=Graphics.preset('planet'),busy=false,recorded=true,epoch=0,capabilities={},sample=null,result=null,uploaded=null;
function state(active){busy=active;for(const id of ['run','preset','resolution','budget','seed','upload','recording','construction','download','png'])$(id).disabled=active||(id==='run'&&!capabilities.live)||(['construction','download','png'].includes(id)&&!result);$('stop').disabled=!active;}
function resetPainting(){result=null;Graphics.draw($('target'),target);Graphics.draw($('painting'),Array(target.length).fill(0x15212a));for(const id of ['layers','pixels','seconds','quality'])$(id).textContent='—';$('source').textContent='';$('snippet').textContent='Waiting for a program…';$('results').textContent='Choose an image and discover a drawing.';$('validation').textContent='NOT YET CHECKED';$('drawing-label').textContent='AWAITING SEARCH';state(false);}
function setPreset(name){uploaded=null;target=Graphics.preset(name,Number($('resolution').value));$('preset').value=name;$('target-name').textContent=$('preset').selectedOptions[0].textContent.toUpperCase();resetPainting();$('status').textContent='READY FOR GPU SEARCH';}
function event(e){const prefix=recorded?'RECORDING · ':'';if(e.kind==='input'){target=e.pixels;$('resolution').value=String(Math.sqrt(target.length));Graphics.draw($('target'),target);$('target-name').textContent='INPUT IMAGE';}if(e.kind==='start'){$('status').textContent=prefix+'SEARCHING DRAWING PROGRAMS';$('drawing-label').textContent=recorded?'RECORDED SEARCH':'LIVE GPU SEARCH';Graphics.draw($('painting'),Graphics.decode(e.image));}if(e.kind==='progress'||e.kind==='done'){$('layers').textContent=e.layers;$('pixels').textContent=((e.pixel_evaluations??e.candidates*16384)/1e9).toFixed(2)+' billion';$('seconds').textContent=e.seconds.toFixed(2)+' s';$('quality').textContent=e.initial_error?((1-e.error/e.initial_error)*100).toFixed(1)+'%':'Exact color';Graphics.draw($('painting'),Graphics.decode(e.image));}if(e.kind==='done'){result=e;$('status').textContent=prefix+'DRAWING COMPLETE';$('drawing-label').textContent=recorded?'RECORDED RESULT':'LIVE RESULT';$('detail').textContent=`First improvement: ${e.first_improvement_seconds===null?'already exact':e.first_improvement_seconds.toFixed(2)+' s'} · ${e.device}`;$('validation').textContent=`${e.gremlin_pixels_checked} EXPORT CHECKS`;$('source').textContent=e.program;$('snippet').textContent=e.program.split('\n').slice(0,8).join('\n')+'\n…';const box=$('results');box.replaceChildren();for(const text of [`${e.width??128} × ${e.height??128} pixels. ${recorded?'Recorded ':''}${e.seconds.toFixed(2)} s search / ${e.total_seconds.toFixed(2)} s through source validation.`,`GPU scoring kernels: ${e.kernel_ms.toFixed(0)} ms. Working buffers: ${(e.device_bytes/1024).toFixed(0)} KiB, excluding the CUDA context.`,`Final GPU image: all ${e.native_pixels_checked.toLocaleString()} pixels match the reference renderer. Gremlin export checked at ${e.gremlin_pixels_checked} sampled pixels.`,`Approximation error: ${e.rmse.toFixed(1)} / 255 RMS per color channel.`]){const p=document.createElement('p');p.textContent=text;box.append(p);}}if(e.kind==='error'){$('status').textContent='ERROR · '+e.message;}if(e.kind==='finished')state(false);}
async function request(path,body){const response=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw Error(data.error||response.statusText);return data;}
function fail(e){$('status').textContent='ERROR · '+e.message;state(false);}
async function poll(id){let after=0;while(id===epoch){const data=await request('/api/events?after='+after);if(id!==epoch)return;for(const e of data.events){event(e);after=e.id;}if(!data.running){state(false);return;}await sleep(100);}}
$('run').onclick=async()=>{const id=++epoch;recorded=false;resetPainting();state(true);$('status').textContent='STARTING GPU';try{await request('/api/run',{target,seed:Number($('seed').value),budget_ms:Number($('budget').value)});await poll(id);}catch(e){fail(e);}};
$('preset').onchange=()=>setPreset($('preset').value);
function loadUpload(){const size=Number($('resolution').value),bitmap=uploaded,c=document.createElement('canvas');c.width=c.height=size;const ctx=c.getContext('2d');ctx.fillStyle='#101820';ctx.fillRect(0,0,size,size);const scale=Math.min(size/bitmap.width,size/bitmap.height),w=bitmap.width*scale,h=bitmap.height*scale;ctx.drawImage(bitmap,(size-w)/2,(size-h)/2,w,h);const pixels=ctx.getImageData(0,0,size,size).data;target=Array.from({length:size*size},(_,p)=>(pixels[p*4]<<16)|(pixels[p*4+1]<<8)|pixels[p*4+2]);resetPainting();$('target-name').textContent='YOUR IMAGE';$('status').textContent='YOUR IMAGE IS READY';}
$('resolution').onchange=()=>{if(uploaded)loadUpload();else setPreset($('preset').value);$('detail').textContent=`${$('resolution').value} × ${$('resolution').value} pixels · GPU search budget depends on layer count`;};
$('upload').onclick=()=>$('file').click();$('file').onchange=async()=>{const file=$('file').files[0];if(!file)return;try{if(file.size>12*1024*1024)throw Error('Choose an image smaller than 12 MB.');const bitmap=await createImageBitmap(file);if(uploaded)uploaded.close();uploaded=bitmap;loadUpload();}catch(e){fail(e);}};
$('recording').onclick=async()=>{const id=++epoch;recorded=true;$('resolution').value='128';setPreset('planet');state(true);try{sample=sample||await request('/sample.json');for(const e of sample.events){if(id!==epoch)return;event(e);await sleep(e.kind==='progress'?180:300);}if(id===epoch)state(false);}catch(e){fail(e);}};
$('stop').onclick=async()=>{if(recorded){++epoch;state(false);$('status').textContent='PLAYBACK STOPPED';}else{try{await request('/api/cancel',{});$('status').textContent='STOPPING SEARCH';}catch(e){fail(e);}}};
$('construction').onclick=()=>{if(!result)return;const id=++epoch,r=result,canvas=Array((r.width??128)*(r.height??128)).fill(r.background);let index=0;state(true);$('stop').disabled=true;$('drawing-label').textContent='CONSTRUCTION PLAYBACK';function frame(){if(id!==epoch)return;for(let n=0;n<8&&index<r.shapes.length;n++)Graphics.paint(canvas,r.shapes[index++]);Graphics.draw($('painting'),canvas);if(index<r.shapes.length)requestAnimationFrame(frame);else{$('drawing-label').textContent=recorded?'RECORDED RESULT':'LIVE RESULT';state(false);}}requestAnimationFrame(frame);};
$('png').onclick=()=>{if(!result)return;const c=document.createElement('canvas');Graphics.draw(c,Graphics.decode(result.image));c.toBlob(blob=>{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`drawing-${result.width??128}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});};
$('download').onclick=()=>{if(!result)return;const url=URL.createObjectURL(new Blob([result.program],{type:'text/plain'})),a=document.createElement('a');a.href=url;a.download='discovered-pixel.gremlin';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
(async()=>{Graphics.draw($('target'),target);try{const s=await request('/api/state');capabilities=s.capabilities;$('connection').textContent=capabilities.live?(capabilities.remote?'REMOTE GPU CONFIGURED':'LOCAL GPU CONFIGURED'):'RECORDED DRAWING AVAILABLE';state(true);if(s.running){recorded=false;await poll(++epoch);}else{sample=await request('/sample.json');recorded=true;event(sample.events.findLast(e=>e.kind==='done'));$('status').textContent='RECORDED DRAWING READY';state(false);}}catch(e){fail(e);}})();
