'use strict';
const $=id=>document.getElementById(id),sleep=ms=>new Promise(r=>setTimeout(r,ms));let result=null,genome=null,recorded=true,busy=false,live=false,epoch=0,animate=true,phase=1.3;
function state(b){busy=b;for(const id of ['run','seed','tolerance','recording'])$(id).disabled=b||(id==='run'&&!live);$('stop').disabled=!b;$('download').disabled=!result;}
function recipe(g){const names=['Newton','Halley','damped Newton','fixed-point'];return `START  ${['E = M','E = π/2','E = M + e/2','E = M + e','if M < 1: M + e; otherwise M + e/4'][g.seed]}\nLOOP   at most ${g.iterations} iterations\nSTEP   ${g.switch===0||g.first===g.later?names[g.later]:`${names[g.first]} for ${g.switch} iterations, then ${names[g.later]}`} \nSTOP   |residual| < ${[0,16,256,4096][g.stop]} / 2²⁸\nGUARD  ${g.guard?'bisect if the step leaves the bracket':'clamp the angle to [0, π]'}\nCAP    ${['no step cap','1 radian','0.5 radians'][g.cap]}`;}
function event(e){if(e.kind==='stage'){$('stage').textContent=e.message;return;}if(e.kind==='progress'){genome=e.genome;$('status').textContent=`EVOLVING · GENERATION ${e.generation}/${e.generations}`;$('executions').textContent=e.evaluations.toLocaleString();$('error').textContent=e.max_error.toExponential(2)+' rad';$('seconds').textContent=e.seconds.toFixed(2)+' s';$('recipe').textContent=recipe(genome);$('stage').textContent=`${e.bad} training cases outside tolerance`;}
 if(e.kind==='done'){result=e;genome=e.genome;$('status').textContent=(recorded?'RECORDED · ':'LIVE · ')+(e.passed?'SOLVER VALIDATED':'ACCURACY TARGET NOT MET');$('executions').textContent=e.evaluations.toLocaleString();$('error').textContent=e.max_error.toExponential(2)+' rad';$('seconds').textContent=e.seconds.toFixed(2)+' s';$('checked').textContent=e.checked.toLocaleString();$('validation').textContent=e.passed?'ALL CHECKED CASES PASS':`${e.failures} CASES FAIL`;$('recipe').textContent=recipe(genome);$('source').textContent=e.source;$('stage').textContent=`${e.device} · ${e.counterexamples??0} counterexamples fed back`;Orbit.heat($('heat'),e.grid,e.tolerance);const box=$('benchmark');box.replaceChildren();const b=e.benchmark;if(b?.available){const p=document.createElement('p');p.textContent=`Compiled program matches the interpreter on ${b.compiled_grid_checked.toLocaleString()} grid inputs.`;box.append(p);if(b.consistent_win){const v=document.createElement('div');v.className='speed';v.textContent=`≥ ${b.speedup.toFixed(2)}× native runtime speedup`;box.append(v);const note=document.createElement('p');note.textContent=`Across all six measured workloads versus the faster of safeguarded Newton and Halley references at the same tolerance. ${b.cpu}. GPU search speed is a separate measurement.`;box.append(note);}}state(busy);}
 if(e.kind==='error'){$('status').textContent='ERROR · '+e.message;}if(e.kind==='finished')state(false);
}
async function request(path,body){const r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||r.statusText);return d;}
async function poll(id){let after=0;while(id===epoch){const d=await request('/api/events?after='+after);for(const e of d.events){if(id!==epoch)return;event(e);after=e.id;}if(!d.running){state(false);return;}await sleep(120);}}
$('run').onclick=async()=>{const id=++epoch;recorded=false;result=null;state(true);$('status').textContent='STARTING GPU SEARCH';$('benchmark').replaceChildren();$('validation').textContent='SEARCHING';try{await request('/api/run',{seed:Number($('seed').value),tolerance:Number($('tolerance').value)});await poll(id);}catch(e){$('status').textContent='ERROR · '+e.message;state(false);}};
$('stop').onclick=()=>request('/api/cancel',{});async function recording(){recorded=true;const s=await request('/sample.json');event(s.events.findLast(e=>e.kind==='done'));state(false);}$('recording').onclick=recording;
$('download').onclick=()=>{if(!result)return;const url=URL.createObjectURL(new Blob([result.source],{type:'text/plain'})),a=document.createElement('a');a.href=url;a.download='discovered-orbit-solver.gremlin';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('animate').onclick=()=>{animate=!animate;$('animate').textContent=animate?'Pause':'Animate';};$('phase').oninput=()=>{phase=Number($('phase').value)/1000;animate=false;$('animate').textContent='Animate';};
$('heat').onclick=e=>{const r=$('heat').getBoundingClientRect();$('ecc').value=Math.round(Math.max(0,Math.min(1,1-(e.clientY-r.top)/r.height))*95);phase=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width))*Math.PI;animate=false;$('animate').textContent='Animate';};
let last=performance.now();function frame(now){if(animate)phase=(phase+Math.min(.1,(now-last)/1000)*.45)%(2*Math.PI);last=now;$('phase').value=Math.round(phase*1000);const e=Number($('ecc').value)/100;$('ecc-value').textContent=e.toFixed(2);const p=Orbit.draw($('orbit'),genome,e,phase);$('point').textContent=`E = ${p.actual.toFixed(6)} rad · angular error ${p.error.toExponential(2)} rad${recorded?' · recorded solver':''}`;requestAnimationFrame(frame);}requestAnimationFrame(frame);
(async()=>{try{const s=await request('/api/state');live=s.capabilities.live;$('connection').textContent=live?'GPU SEARCH CONNECTED':'RECORDED DEMO';if(s.running){recorded=false;state(true);await poll(++epoch);}else await recording();}catch(e){$('status').textContent=e.message;state(false);}})();
