'use strict';
const $=id=>document.getElementById(id), number=n=>Number(n).toLocaleString('en-US');
const actions=['Move forward','Turn left','Turn right','Turn around'];
let room=Robot.fresh(),brain=null,trace=null,frame=0,playing=false,lastTick=0,tool='wall',dragging=false,paintWall=true;
let epoch=0,busy=false,recording=false,capabilities={},sample=null,examples=[],exampleKind='Unseen test rooms';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function state(active){busy=active;for(const id of ['train','cases','seed','replay'])$(id).disabled=active||(id==='train'&&!capabilities.live);$('stop').disabled=!active;}
function setPlaying(value){playing=value&&!!trace;lastTick=performance.now();$('play').textContent=playing?'Pause Ⅱ':'Run this brain ▶';}
function recalculate(){setPlaying(false);frame=0;const error=Robot.validate(room);trace=brain&&!error?Robot.simulate(brain,room):null;$('outcome').textContent=error||'Ready to explore';for(const id of ['play','step','reset'])$(id).disabled=!trace;draw();}
function setRoom(value,kind){room=JSON.parse(JSON.stringify(value));$('room-type').textContent=kind;recalculate();}
function pretty(source){let indent=0;return source.replace(/([{};])/g,'$1\n').split('\n').map(s=>s.trim()).filter(Boolean).map(s=>{if(s.startsWith('}'))indent--;const line='  '.repeat(Math.max(0,indent))+s;if(s.endsWith('{'))indent++;return line;}).join('\n');}
function setBrain(e,label){brain=e.decisions.slice();$('brain-label').textContent=label;$('source').textContent=pretty(e.brain_source);const tbody=$('rules');tbody.replaceChildren();for(let row=0;row<16;row++){const tr=document.createElement('tr');tr.dataset.row=row;for(const text of [row>>3,row&1?'open':'wall',row&2?'open':'wall',row&4?'open':'wall',actions[brain[row]&3],brain[row]>>2]){const td=document.createElement('td');td.textContent=text;tr.append(td);}tbody.append(tr);}recalculate();}
function icon(ctx,kind,x,y,size,heading=0){ctx.save();ctx.translate(x,y);ctx.lineWidth=size*.09;if(kind==='key'){ctx.strokeStyle='#a97814';ctx.beginPath();ctx.arc(-size*.14,0,size*.17,0,Math.PI*2);ctx.moveTo(size*.03,0);ctx.lineTo(size*.35,0);ctx.lineTo(size*.35,size*.14);ctx.moveTo(size*.23,0);ctx.lineTo(size*.23,size*.1);ctx.stroke();}if(kind==='door'){ctx.fillStyle='#d8945b';ctx.fillRect(-size*.27,-size*.35,size*.54,size*.7);ctx.strokeStyle='#795036';ctx.strokeRect(-size*.27,-size*.35,size*.54,size*.7);ctx.fillStyle='#553d32';ctx.fillRect(size*.09,-size*.03,size*.07,size*.07);}if(kind==='exit'){ctx.strokeStyle='#9c63a1';ctx.beginPath();ctx.arc(0,0,size*.3,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(-size*.15,0);ctx.lineTo(size*.16,0);ctx.lineTo(size*.04,-size*.11);ctx.moveTo(size*.16,0);ctx.lineTo(size*.04,size*.11);ctx.stroke();}if(kind==='robot'){ctx.rotate(heading*Math.PI/2);ctx.fillStyle='#253849';ctx.fillRect(-size*.32,-size*.13,size*.13,size*.38);ctx.fillRect(size*.19,-size*.13,size*.13,size*.38);ctx.fillStyle='#f7c971';ctx.beginPath();ctx.roundRect(-size*.24,-size*.29,size*.48,size*.55,size*.11);ctx.fill();ctx.fillStyle='#263d48';ctx.beginPath();ctx.roundRect(-size*.16,-size*.19,size*.32,size*.15,size*.06);ctx.fill();ctx.fillStyle='#d9f1e2';ctx.fillRect(-size*.1,-size*.16,size*.055,size*.04);ctx.fillRect(size*.045,-size*.16,size*.055,size*.04);}ctx.restore();}
function board(canvas,r,frames,index,mini=false){const ctx=canvas.getContext('2d'),size=canvas.width/8;const f=frames?.[index]||[r.start,r.heading,0,false],visited=new Set(frames?.slice(0,index+1).map(x=>x[0])||[]);ctx.fillStyle='#0f1c25';ctx.fillRect(0,0,canvas.width,canvas.height);for(let p=0;p<64;p++){const x=(p%8)*size,y=Math.floor(p/8)*size;if(Robot.wall(r,p)){ctx.fillStyle='#263945';ctx.fillRect(x+1,y+1,size-2,size-2);if(!mini){ctx.fillStyle='#324650';ctx.fillRect(x+5,y+5,size-10,2);}}else{ctx.fillStyle=visited.has(p)?'#c6dfc0':'#e2e9d9';ctx.fillRect(x+1,y+1,size-2,size-2);}}
 if(!mini&&frames){ctx.strokeStyle='#5d9c8366';ctx.lineWidth=3;ctx.beginPath();for(let i=0;i<=index;i++){const p=frames[i][0],x=(p%8+.5)*size,y=(Math.floor(p/8)+.5)*size;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.stroke();}
 const item=(kind,p)=>icon(ctx,kind,(p%8+.5)*size,(Math.floor(p/8)+.5)*size,size*.8);
 item('exit',r.exit);if(!f[3]){item('key',r.key);item('door',r.door);}else{ctx.strokeStyle='#d8945b';ctx.lineWidth=2;ctx.strokeRect((r.door%8)*size+size*.22,Math.floor(r.door/8)*size+size*.12,size*.56,size*.76);}
 if(!mini){const senses=Robot.sensors(r,f[0],f[1],f[3]);[f[1],(f[1]+3)&3,(f[1]+1)&3].forEach((d,i)=>{const p=Robot.neighbor(f[0],d);ctx.strokeStyle=senses[i]?'#5b977c':'#cf845a';ctx.lineWidth=3;ctx.strokeRect((p%8)*size+5,Math.floor(p/8)*size+5,size-10,size-10);});}
 icon(ctx,'robot',(f[0]%8+.5)*size,(Math.floor(f[0]/8)+.5)*size,size*.8,f[1]);}
function draw(){board($('room'),room,trace?.frames,frame);if(!trace){for(const id of ['front','left','right','memory'])$(id).textContent='—';$('decision').textContent=brain?'Edit the room to continue':'Waiting for a brain';$('next-memory').textContent='';$('actions').textContent='0 / 256 actions';for(const tr of $('rules').children)tr.classList.remove('active');return;}const f=trace.frames[frame],[front,left,right]=Robot.sensors(room,f[0],f[1],f[3]);for(const [id,open] of [['front',front],['left',left],['right',right]])$(id).textContent=open?'OPEN':'WALL';$('memory').textContent=f[2];const row=Number(front)+2*Number(left)+4*Number(right)+8*f[2],instruction=brain[row];const finished=frame===trace.frames.length-1;$('decision').textContent=finished?(trace.solved?'Exit reached':'Action limit reached'):actions[instruction&3];$('next-memory').textContent=finished?'Episode complete':`memory ${f[2]} → ${instruction>>2} · ${f[3]?'key collected':'key not collected'}`;for(const tr of $('rules').children)tr.classList.toggle('active',Number(tr.dataset.row)===row&&!finished);$('actions').textContent=`${frame} / 256 actions`;$('outcome').textContent=finished?(trace.solved?`Escaped in ${trace.steps} actions!`:'Not solved within 256 actions'):(playing?'Exploring…':frame?'Paused':'Ready to explore');}
function advance(){if(!trace)return;if(frame<trace.frames.length-1)frame++;if(frame===trace.frames.length-1)setPlaying(false);draw();}
$('play').onclick=()=>{if(!trace)return;if(frame===trace.frames.length-1)frame=0;setPlaying(!playing);draw();};$('step').onclick=()=>{setPlaying(false);advance();};$('reset').onclick=()=>recalculate();$('fresh').onclick=()=>setRoom(Robot.fresh(),'FRESH MAZE');$('rotate').onclick=()=>{room.heading=(room.heading+1)&3;$('room-type').textContent='YOUR ROOM';recalculate();};
for(const button of document.querySelectorAll('[data-tool]'))button.onclick=()=>{tool=button.dataset.tool;for(const other of document.querySelectorAll('[data-tool]'))other.classList.toggle('selected',other===button);};
function cell(event){const rect=$('room').getBoundingClientRect();return Math.min(7,Math.max(0,Math.floor((event.clientX-rect.left)/rect.width*8)))+8*Math.min(7,Math.max(0,Math.floor((event.clientY-rect.top)/rect.height*8)));}
function paint(p,first){if(!Robot.inside(p))return;const occupied=['start','key','door','exit'];if(tool==='wall'){if(occupied.some(k=>room[k]===p))return;if(first)paintWall=!Robot.wall(room,p);let bits=BigInt('0x'+room.walls);bits=paintWall?bits|(1n<<BigInt(p)):bits&~(1n<<BigInt(p));room.walls=bits.toString(16).padStart(16,'0');}else{if(occupied.some(k=>k!==tool&&room[k]===p))return;room[tool]=p;room.walls=(BigInt('0x'+room.walls)&~(1n<<BigInt(p))).toString(16).padStart(16,'0');}$('room-type').textContent='YOUR ROOM';recalculate();}
$('room').onpointerdown=e=>{dragging=true;$('room').setPointerCapture(e.pointerId);paint(cell(e),true);};$('room').onpointermove=e=>{if(dragging&&tool==='wall')paint(cell(e),false);};$('room').onpointerup=()=>{dragging=false;};$('room').onpointercancel=()=>{dragging=false;};
function gallery(previews,kind){examples=previews;exampleKind=kind;$('examples-title').textContent=kind;const container=$('gallery');container.replaceChildren();for(const e of previews){const b=document.createElement('button'),c=document.createElement('canvas'),label=document.createElement('span');c.width=c.height=112;board(c,e.room,e.frames,e.frames.length-1,true);label.textContent=e.solved?'ESCAPED':'UNSOLVED';b.append(c,label);b.onclick=()=>setRoom(e.room,kind==='Unseen test rooms'?'UNSEEN TEST':'TRAINING SAMPLE');container.append(b);}}
function progress(e){const prefix=recording?'RECORDING · ':'';if(e.kind==='start'){$('status').textContent=prefix+'EVOLVING ON GPU';$('holdout').textContent='Not tested';$('detail').textContent=`256 random brains · ${e.cases} training rooms`;}if(e.kind==='progress'||e.kind==='done'){$('solved').textContent=`${e.solved} / ${e.cases}`;$('generation').textContent=e.generation;$('episodes').textContent=number(e.evaluations);setBrain(e,recording?'RECORDED BRAIN':'EVOLVED BRAIN');gallery(e.previews,e.kind==='done'?'Unseen test rooms':'Sample training rooms');if(e.kind==='progress'){setPlaying(true);$('detail').textContent=`${e.seconds.toFixed(1)} s · ${e.device}`;}else{$('holdout').textContent=`${e.holdout_solved} / ${e.holdout_cases}`;$('status').textContent=prefix+(e.converged?'TRAINING COMPLETE':'SEARCH BUDGET REACHED');$('detail').textContent=`${e.seconds.toFixed(1)} s · ${(e.peak_bytes/1048576).toFixed(0)} MiB peak device memory`;$('evidence').textContent=`${recording?'RECORDED':'LIVE'} GPU SEARCH · ${number(e.evaluations)} INDEPENDENT SIMULATOR CHECKS`;}}if(e.kind==='curriculum'){$('status').textContent=prefix+'EXPANDING TRAINING SET';$('detail').textContent=`Solved ${e.from} rooms; re-evaluating on ${e.to}.`;}if(e.kind==='error'){$('status').textContent='ERROR · '+e.message;}if(e.kind==='finished')state(false);}
async function request(path,body){const response=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw Error(data.error||response.statusText);return data;}
function fail(error){$('status').textContent='ERROR · '+error.message;state(false);}
async function poll(id){let after=0;while(id===epoch){const data=await request('/api/events?after='+after);if(id!==epoch)return;for(const e of data.events){progress(e);after=e.id;}if(!data.running){state(false);return;}await sleep(350);}}
$('train').onclick=async()=>{const id=++epoch;recording=false;state(true);$('status').textContent='STARTING GPU SEARCH';try{await request('/api/run',{mode:'gpu',preset:'robot',cases:Number($('cases').value),seed:Number($('seed').value)});await poll(id);}catch(e){fail(e);}};
$('replay').onclick=async()=>{const id=++epoch;recording=true;state(true);try{sample=sample||await request('/sample.json');for(const e of sample.events){if(id!==epoch)return;progress(e);await sleep(e.kind==='progress'?850:500);}if(id===epoch)state(false);}catch(e){fail(e);}};
$('stop').onclick=async()=>{if(recording){++epoch;state(false);$('status').textContent='RECORDING STOPPED';}else{try{await request('/api/cancel',{});$('status').textContent='STOPPING GPU SEARCH';}catch(e){fail(e);}}};
function animate(now){if(playing&&now-lastTick>1000/Number($('speed').value)){lastTick=now;advance();}requestAnimationFrame(animate);}draw();requestAnimationFrame(animate);
(async()=>{try{const s=await request('/api/state');capabilities=s.capabilities;$('connection').textContent=capabilities.live?(capabilities.remote?'REMOTE GPU CONFIGURED':'LOCAL GPU CONFIGURED'):'RECORDED BRAIN + ROOM EDITOR';state(true);if(s.running){recording=false;await poll(++epoch);}else{sample=await request('/sample.json');recording=true;const done=sample.events.findLast(e=>e.kind==='done');progress(done);$('status').textContent='RECORDED BRAIN READY';setRoom(Robot.fresh(),'FRESH MAZE');state(false);}}catch(e){fail(e);}})();
